### ISSUE TITLE
Can't run the application

### ISSUE THREAD

**Issue by matq007** [wys8c764/CSN#3]
Hi,

I am having issues running your scripts. I have tried to run the code below, but I am getting an error:

```matlab
>> matrix = readtable("normalized-matrix.txt", 'ReadRowNames', true);
>> ndm_matrix = csndm(matrix);
Error using tabular/sort
Too many output arguments.

Error in csndm (line 25)
    [s1,s2] = sort(data(i,:));
```

Do you know what might be wrong?
Thank you.

**Comment by zoomlion** [comment]
Maybe you should change table format to matrix format to use the sort method in this script?
