### ISSUE TITLE
The performance issue

### ISSUE THREAD

**Issue by zoomlion** [wys8c764/CSN#5]
It takes quite a long time (over 15h) when dealing with a **GEM** (gene expression matrix) at the size of (_16459*11657_). 
> Running csndm.m

Is the performance directly correlated with the size of the matrix. I'm considering filtering those genes expressed in fewer than N cells (N could be tested, e..g 10). Considering ultra-fast speed for matrix calculation (in Matlab), I think the large size of GEM is the reason for low speed.

**Another Issue**
The second step is not feasible when dealing with this matrix, maybe MatLab on PC (especially without enough memory) is not the best choice for running this program. Rebuild the code in some other programming language might be one better choice.

**Comment by handesome** [comment]
> It takes quite a long time (over 15h) when dealing with a **GEM** (gene expression matrix) at the size of (_16459*11657_).
> 
> > Running csndm.m
> 
> Is the performance directly correlated with the size of the matrix. I'm considering filtering those genes expressed in fewer than N cells (N could be tested, e..g 10). Considering ultra-fast speed for matrix calculation (in Matlab), I think the large size of GEM is the reason for low speed.
> 
> **Another Issue** The second step is not feasible when dealing with this matrix, maybe MatLab on PC (especially without enough memory) is not the best choice for running this program. Rebuild the code in some other programming language might be one better choice.

hi,zoomlion,could you give an example to show how  to run?

**Comment by zoomlion** [comment]
Really sorry, It has been long days since I raised this issue. Original data were discarded =(
Seems still slow when dealing with large gene matrix. I suggest you try some other methods to deal with gene expression network.

**Comment by handesome** [comment]
that's so bad
